### ISSUE TITLE
[FollowMe] Improving demo

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/follow-me#10]
Propongo la posibilidad de mejorar la demo de "Follow me" (puesto que actualmente es la única que está operativa) añadiendo algo más credibilidad y vistosidad para cuando alguien quiera ver a Teo. Por ejemplo, se pueden intentar añadir cosas "sencillas" como: en el momento en que Teo dice las frases: "Hi, I am ready" y "ok, I am following you",  acompañar ambas frases con un movimiento del brazo derecho de gesticulación y en el momento en que comience a mover la cabeza para seguir al sujeto, pasar al movimiento de balanceo de brazos. ¿Qué os parece? ¿Consideráis que merece la pena o que no es prioritario mejorar la demo?
Saludos cordiales

**Comment by jgvictores** [comment]
A falto de probar en el robot real (probado en simulador), implementado en 67d591ded11f64d8f8b327300961b543c494614f.

**Comment by jgvictores** [comment]
Probado en real, funciona.
