### ISSUE TITLE
[Error] followMeExecutionCore

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/follow-me#14]
En diversas ocasiones se ha mostrado un error en el Yarp Manager al cargar el módulo "followMeExecutionCore":
`[ERR] (follow-me_App) cannot run followMeExecutionCore on localhost.`
Soluciones a probar  (sugerido por @jgvictores ): Attach to stdout y copiar output, lanzar desde consola y ver error...

**Comment by jgvictores** [comment]
Intuyo que falla cuando falla algún componente de teoBase, pero stdout y stderr nos darán más info.

**Comment by rsantos88** [comment]
De momento, se ha resuelto el problema. En caso de volver a dar algún fallo, se reabrirá esta issue.
Gracias @jgvictores
