### ISSUE TITLE
Update follow-me-state-machine.png

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/follow-me#22]
Update follow-me-state-machine.png

**Comment by rsantos88** [comment]
¿Qué tal lo ves @jgvictores ?
![follow-me-state-machine updated](https://cloud.githubusercontent.com/assets/15872457/20975115/b7c65bec-bc9e-11e6-93f1-b214094a748f.png)

**Comment by jgvictores** [comment]
Looks good to me! 

Puedes meter en repo imagen y fuente si no está ya? 
Thanks!

**Comment by rsantos88** [comment]
I've just done it! (2277c8d5a14e1cca921b58ab16f4b9859dd0ce13)

**Comment by jgvictores** [comment]
@rsantos88 Thanks!
