### ISSUE TITLE
Must update follow-me-app.png

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/follow-me#33]
Must update [doc/fig/follow-me-app.png](https://github.com/roboticslab-uc3m/follow-me/blob/c1ba54c3b61c999836419587aef5d1d5586dd2bd/doc/fig/follow-me-app.png), from source [doc/fig/editable/follow-me-app.graphml](https://github.com/roboticslab-uc3m/follow-me/blob/c1ba54c3b61c999836419587aef5d1d5586dd2bd/doc/fig/editable/follow-me-app.graphml), with new repo names: `yarp-devices`, `vision`, etc.

**Comment by rsantos88** [comment]
Done it at (f2f116e57d5536974e46e81988dbb5fe330bea4b)
I'll close this issue!!

**Comment by jgvictores** [comment]
Maybe green could be used for `speech` and we can put `speechRecognition.py` in green?

**Comment by jgvictores** [comment]
PS: As well as `yarpdev --device Espeak`.

**Comment by jgvictores** [comment]
Something like `speech @ /head`.

**Comment by rsantos88** [comment]
updated it! (01e088935e9d6742b1028306dc89109a58119b7f)

**Comment by jgvictores** [comment]
@rsantos88 Thanks, really great!
