### ISSUE TITLE
Proposal of renaming to teo-follow-me

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/follow-me#34]
Proposal of renaming to teo-follow-me, as this repo has become very teo-specific.

...or make it less teo-specific!?

**Comment by PeterBowman** [comment]
> ...or make it less teo-specific!?

I'm working on a 2D haarTraining app on roboticslab-uc3m/vision and its controller counterpart at kinematics-dynamics, with a much simpler purpose: fetch object centroids from the grabber device and make the robot move towards the target until it's deemed close enough by a proximity sensor (or some other signal), then close the gripper tool (if available). I feel it could be part of something bigger, and this repo already has ASR support.

**Comment by PeterBowman** [comment]
> I'm working on a 2D haarTraining app on roboticslab-uc3m/vision and its controller counterpart at kinematics-dynamics

* [haarDetection2D@vision](https://github.com/roboticslab-uc3m/vision/tree/d7d36763625150bcc4eb7493f4c07f3f5495678d/programs/haarDetection2D)
* [haarDetectionController@kinematics-dynamics](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/bf74e7afa2e0d3f76ba3cc032b44c91dd6a340e8/programs/haarDetectionController)

Regarding that simple visual servo app, at first aimed to control AMOR, I think it could fit TEO as well given some obvious enhancements (involving frame transformations). All that might land in a new repo oriented to visual servo + approach (+ final grasp?) tasks, leaving (teo-)follow-me as is.

**Comment by PeterBowman** [comment]
> Proposal of renaming to teo-follow-me, as this repo has become very teo-specific.

I'm giving my +1 as it is specifically designed for TEO. Nothing stops us from reusing it on other *compatible* robots, though, in which case I think a teo- prefix would not bother me anyway.

**Comment by jgvictores** [comment]
Okay, did the quick rename...

Apart from updating the README (atow, pending), what other changes should this involve (CMake variables, file renaming...)?

**Comment by PeterBowman** [comment]
@jgvictores please leave it as is, I'm working on this repo right now. I'll take care as soon as it's ready.

**Comment by PeterBowman** [comment]
Done at https://github.com/roboticslab-uc3m/teo-follow-me/commit/c911b29a4455bec6a0ca3801d8f56cce4b6c09db except [teo-follow-me-app.graphml](https://github.com/roboticslab-uc3m/teo-follow-me/blob/a8062e56fb56bfeb52fe96c91cf686dd6ae75657/doc/fig/editable/teo-follow-me-app.graphml) (note I did update [teo-follow-me-app.svg](https://github.com/roboticslab-uc3m/teo-follow-me/blob/a8062e56fb56bfeb52fe96c91cf686dd6ae75657/doc/fig/teo-follow-me-app.svg)).

**Comment by jgvictores** [comment]
> Done at [c911b29](https://github.com/roboticslab-uc3m/teo-follow-me/commit/c911b29a4455bec6a0ca3801d8f56cce4b6c09db) except [teo-follow-me-app.graphml](https://github.com/roboticslab-uc3m/teo-follow-me/blob/a8062e56fb56bfeb52fe96c91cf686dd6ae75657/doc/fig/editable/teo-follow-me-app.graphml) (note I did update [teo-follow-me-app.svg](https://github.com/roboticslab-uc3m/teo-follow-me/blob/a8062e56fb56bfeb52fe96c91cf686dd6ae75657/doc/fig/teo-follow-me-app.svg)).

Did `.graphml` file at https://github.com/roboticslab-uc3m/teo-follow-me/commit/abc6f80b9b1a76ce3df65ed9aa8e36490355ecff and added related `README.md`.
