### ISSUE TITLE
Update follow-me-app.graphml

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/follow-me#36]
I believe the PNG generated and shown in the main page is not the same as seen in the .graphml file.

Related: roboticslab-uc3m/yarp-devices#99.

**Comment by jgvictores** [comment]
Agreed. Added to toDo.

**Comment by jgvictores** [comment]
Closed via https://github.com/roboticslab-uc3m/follow-me/commit/33a61835b29a7b084ee3f65929c5e41ce69226bb

**Comment by jgvictores** [comment]
Now vector at https://github.com/roboticslab-uc3m/follow-me/commit/d585a718905028b5540aeadc447c2f3d50dfeb6a
