### ISSUE TITLE
Update follow-me-app.png

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/follow-me#4]
Update [follow-me-app.png](https://github.com/roboticslab-uc3m/follow-me/blob/master/doc/fig/follow-me-app.png)

**Comment by rsantos88** [comment]
Now, the picture is updated with new module names ([follow-me-app.png](https://raw.githubusercontent.com/roboticslab-uc3m/follow-me/develop/doc/fig/follow-me-app.png)) and also, it has been added a editable [file](https://github.com/roboticslab-uc3m/follow-me/blob/develop/doc/fig/editable/follow-me-app.graphml).

**Comment by rsantos88** [comment]
@jgvictores do you think  we have to add two modules, head move and the arm swing separately instead of launchManipulation module??

**Comment by jgvictores** [comment]
> @jgvictores do you think  we have to add two modules, head move and the arm swing separately instead of launchManipulation module??

Tecnhical issues (canBus) make them kind of inseparateable.

BTW, could you update the blue `teo-main` -> `teo-head` in the legend?

**Comment by rsantos88** [comment]
Yes, of course ([link](https://raw.githubusercontent.com/roboticslab-uc3m/follow-me/develop/doc/fig/follow-me-app.png))

**Comment by jgvictores** [comment]
Thanks! The diagram looks good to me!

@rsantos88 I think no new connections are needed, in any case we could comment that on #18. Closing this one!

**Comment by jgvictores** [comment]
Reopening, missing arm swing.

**Comment by rsantos88** [comment]
![follow-me-app with followmearmswing](https://cloud.githubusercontent.com/assets/15872457/21106085/07494e6c-c08d-11e6-9edb-fd03b059e384.png)
¿How do you see it @jgvictores ?

**Comment by jgvictores** [comment]
Looks good to me!

Maybe we could think about renaming the components, but that would be another issue!

**Comment by rsantos88** [comment]
Perfect, I will update the changes!

**Comment by jgvictores** [comment]
Thanks!

**Comment by rsantos88** [comment]
Done it! (4062ee64540b125933bf67d4c7525a7fa1245f42)

**Comment by jgvictores** [comment]
@rsantos88 Great! Closing issue!
