### ISSUE TITLE
Add mute/unmute microphone to this demo

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/follow-me#40]
The idea is mute the microphone when Teo is talking something and we don't want to capture the noise.

**Comment by rsantos88** [comment]
I copy [this](https://github.com/roboticslab-uc3m/speech/issues/13#issuecomment-381989664) issue which involves this demo:
>Here we've a limitation. We can mute or unmute the microphone by software automatically, sending the demonstration commands to speechRecognition when the robot is speaking or in a moments when we know for sure we're not going to talk. But, the problem here is what happen when the robot is waiting for an order and at the same time is doing something.
E.g: Teo is following you but it's checking all the time if you are going to say "stop". Here, we can take the option to mute all the time the microphone, but we can't stop him by command voice. If we don't mute the microphone, Teo will receive to much noise and false orders.
>
>At this point, any possible idea of how to resolve that with the work done ?

**Comment by rsantos88** [comment]
Possible solutions:
* As @PeterBowman propoused: 
>One thing I can come up with are acknowledgements. That is, make TEO send an Are you sure? notice back to you, and await confirmation. Is it feasible in your demo workflow?
* filter the noise with greater concatenation of words: E.g `please stop TEO` instead of `stop` but I want to get a solution to avoid modifying the dictionaries...

**Comment by rsantos88** [comment]
Other idea (I like it):
1. (every 2 or 3 minutes) Teo: "If you want me to stop following you, please say: **stop** "
2. `setMic unmute` (wait 2 seconds)
-- You: "wait" -> `setMic mute` & Teo: "ok, I will stop following you..."
-- You: "...."   -> Teo continues following

**Comment by rsantos88** [comment]
Before continue with all of this, I prefer to know what @jgvictores  thinks personally

**Comment by rsantos88** [comment]
As I talked with @jgvictores , we can left this demostration with this changes ([see PR](https://github.com/roboticslab-uc3m/follow-me/pull/42)) by the moment: only mute the microphone when Teo is speaking but take into account that the problem [aforementioned](https://github.com/roboticslab-uc3m/follow-me/issues/40#issuecomment-382017078) still persists

Can I close this issue?

**Comment by jgvictores** [comment]
Merged #42. Yes, feel free to close it.

I'll probably open new, specific issues.
