### ISSUE TITLE
Update joint-space commands

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/follow-me#46]
Update joint-space commands, changed at https://github.com/roboticslab-uc3m/teo-main/issues/39

**Comment by rsantos88** [comment]
Pull request: https://github.com/roboticslab-uc3m/follow-me/pull/47 (not tested yet on Teo)

**Comment by jgvictores** [comment]
https://github.com/roboticslab-uc3m/follow-me/pull/47 merged at https://github.com/roboticslab-uc3m/follow-me/commit/1de3bae77c52681117a8cdfe1cbce7ae30f3a9c2
@rsantos88 please close!
